/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Noss (https://sketchfab.com/Noss)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/models/c29e6775218b4ec9b345677660a17a24
title: Day 20 - Minimalistic : Split
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Giraffe() {
  const { nodes, materials } = useGLTF("/giraffe.glb");
  return (
    <group rotation={[-Math.PI / 2, 0, 0]}>
      <group position={[0.11, 0, 0]} rotation={[0, 0, 0.45]} scale={1.03}>
        <mesh
          geometry={nodes.girafe_0.geometry}
          material={materials.simple_wood}
        />
      </group>
      <mesh geometry={nodes.cyclo_0.geometry} material={materials.cyclo} />
    </group>
  );
}

useGLTF.preload("/giraffe.glb");
